
#server.port=8080

server:
  port: 8088

uname: lisi
age: 24

animal: # 定义对象
  name: Sunny
  age: 12
friend: {fname: Oscar,age: 20} # 对象的行内写法

# 数组 list set定义
pets:
- cat
- dog
- fish
names: [cat,dog,fish] # 行内写法

person:
  userName: zhangsan
  boss: false
  birth: 2019/12/12 20:12:33
  age: 18
  pet:
    name: tomcat
    weight: 23.4
  interests: [篮球,游泳]
  animal:
  - jerry
  - mario
  score:
    english:
      first: 30
      second: 40
      third: 50
    math: [131,140,148]
    chinese: {first: 128,second: 136}
  salarys: [3999,4999.98,5999.99]
  allPets:
    sick:
    - {name: tom}
    - {name: jerry,weight: 47}
    health: [{name: mario,weight: 47}]

demo2:
  name1: 'zhangsan \n lisi' # 将/n转义成换行
  name2: "zhangsan \n lisi" # 不会转义